# Generated by Django 2.2.6 on 2019-10-29 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='credit',
            new_name='amount',
        ),
        migrations.AlterField(
            model_name='loan',
            name='payment_complete_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
